---
configs:
  postgresql:
    content: |
      effective_cache_size = 64MB
      listen_addresses = '*'
      maintenance_work_mem = 2MB
      max_connections = 10
      shared_buffers = 16MB
      work_mem = 1MB

services:
  postgresql:
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    configs:
      - gid: "70"
        mode: 0440
        source: postgresql
        target: /etc/postgresql/postgresql.conf
        uid: "70"
    depends_on:
      postgresql_init:
        condition: service_completed_successfully
    environment:
      POSTGRES_PASSWORD_FILE: /state/secrets/postgresql-root-user-password.txt
    extends:
      file: compose.templates.yml
      service: service
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -d
        - postgres
        - -U
        - postgres
    image: postgres:17.4-alpine3.21
    networks:
      - identity_provider
    volumes:
      - ./state/postgresql/data:/var/lib/postgresql/data
      - ./state/secrets:/state/secrets

  postgresql_init:
    command:
      - |
          POSTGRESQL_ROOT_USER_PASSWORD_FILE=/state/secrets/postgresql-root-user-password.txt
          if [ ! -f "$$POSTGRESQL_ROOT_USER_PASSWORD_FILE" ]; then
            tr -dc A-Za-z0-9 < /dev/urandom | head -c 32 > "$$POSTGRESQL_ROOT_USER_PASSWORD_FILE"
            chmod 0400 "$$POSTGRESQL_ROOT_USER_PASSWORD_FILE"
            chown 70:70 "$$POSTGRESQL_ROOT_USER_PASSWORD_FILE"
          fi
    deploy:
      resources:
        limits:
          memory: 16M
    extends:
      file: compose.templates.yml
      service: job
    image: postgres:17.4-alpine3.21
    networks:
      - identity_provider
    volumes:
      - ./state/secrets:/state/secrets
...
