---
services:
  zitadel_init:
    command:
      - |
          if [ ! -f "$$ZITADEL_MASTER_KEY_FILE" ]; then
            tr -dc A-Za-z0-9 < /dev/urandom | head -c 32 > "$$ZITADEL_MASTER_KEY_FILE"
            zitadel init --config "$$ZITADEL_CONFIG_FILE"
          fi
    configs:
      - gid: "1000"
        mode: 0440
        source: zitadel_config
        target: /etc/zitadel/zitadel.yml
        uid: "1000"
    depends_on:
      postgresql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 64M
    environment:
      ZITADEL_CONFIG_FILE: /etc/zitadel/zitadel.yml
      ZITADEL_MASTER_KEY_FILE: /state/secrets/zitadel-master-key.txt
    extends:
      file: compose.templates.yml
      service: job
    image: ghcr.io/zitadel/zitadel:v2.71.3-debug
    networks:
      - identity_provider
    volumes:
      - ./state/secrets:/state/secrets
...
