---
services:
  zitadel_init:
    command:
      - |
          STATE_FILE=/state/zitadel/initialized
          mkdir -p "$(dirname "$$STATE_FILE")"
          if [ ! -f "$$STATE_FILE" ]; then
            zitadel init --config /etc/zitadel/zitadel.yml
            echo "$(date +%s)" > "$$STATE_FILE"
          fi
    depends_on: !override
      postgresql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 64M
    entrypoint: bash -c
    extends:
      file: compose.service.zitadel.yml
      service: zitadel
    healthcheck:
      test: !reset null
    image: ghcr.io/zitadel/zitadel:v2.71.3-debug
    labels: !reset []
    networks: !override
      - identity_provider
    restart: no
    user: root
    volumes:
      - ./state:/state
...
