---
services:
  zitadel_init:
    command:
      - |
          STATE_FILE=/state/zitadel/initialized
          if [ ! -f "$$STATE_FILE" ]; then
            zitadel init --config /etc/zitadel/zitadel.yml
            echo "$(date +%s)" > "$$STATE_FILE"
          fi
    configs:
      - gid: "1000"
        mode: 0440
        source: zitadel_config
        target: /etc/zitadel/zitadel.yml
        uid: "1000"
    depends_on:
      postgresql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 64M
    extends:
      file: compose.templates.yml
      service: job
    image: ghcr.io/zitadel/zitadel:v2.71.3-debug
    networks:
      - identity_provider
    volumes:
      - ./state/zitadel:/state/zitadel
...
