---
# @TODO: Needs fully compatible and transparent podman-compose support
x-podman:
  in_pod: false

x-templates:
  service: &service
    healthcheck: &service-healthcheck
      interval: 10s
      start_interval: 2s
      start_period: 10s
      timeout: 3s
    mem_swappiness: 0
    networks:
      - identity-provider
    restart: unless-stopped
    security_opt:
      - label:disable
    userns_mode: keep-id:uid=0,gid=0

  job: &job
    <<: *service
    restart: "no"

configs:
  pgbouncer-userlist:
    content: |
      "postgres" "${DATABASE_ROOT_USER_PASSWORD:?}"

  postgresql:
    content: |
      effective_cache_size = 64MB
      listen_addresses = '*'
      maintenance_work_mem = 2MB
      max_connections = 10
      shared_buffers = 16MB
      work_mem = 1MB

  zitadel-config:
    content: |
      ---
      Database:
        postgres:
          Admin:
            Password: ${DATABASE_ROOT_USER_PASSWORD:?}
            Username: postgres
            SSL:
              Mode: disable
          Database: zitadel
          Host: pgbouncer
          MaxConnIdleTime: 5m
          MaxConnLifetime: 1h
          MaxIdleConns: 5
          MaxOpenConns: 20
          Port: 5432
          User:
            Password: ${DATABASE_USER_PASSWORD:?}
            Username: zitadel
            SSL:
              Mode: disable
      ExternalDomain: ${HOSTNAME:?}
      ExternalPort: 443
      Machine:
        Identification:
          PrivateIp:
            Enabled: false
          Hostname:
            Enabled: true
          Webhook:
            Enabled: false
      Metrics:
        Type: none
      Notifications:
        LegacyEnabled: false
      SystemDefaults:
        KeyConfig:
          CertificateLifetime: 4320h
          PrivateKeyLifetime: 1h
          PublicKeyLifetime: 12h
          Size: 4096
        Multifactors:
          OTP:
            Issuer:
        PasswordHasher:
          Hasher:
            Algorithm: argon2id
            Hash: sha512
        SecretHasher:
          Hasher:
            Algorithm: argon2id
            Hash: sha512
        SecretGenerators:
          ApplicationKeySize: 4096
          MachineKeySize: 4096
      TLS:
        Enabled: false
      ...

  zitadel-steps:
    content: |
      ---
      FirstInstance:
        InstanceName: ${HOSTNAME:?}
        Org:
          Name: ${ZITADEL_ORGANIZATION_NAME:?}
          Human:
            DisplayName: ${ZITADEL_USER_FIRST_NAME:?} ${ZITADEL_USER_LAST_NAME:?}
            Email:
              Address: ${ZITADEL_USER_EMAIL_ADDRESS:?}
              Verified: true
            FirstName: ${ZITADEL_USER_FIRST_NAME:?}
            Gender: ${ZITADEL_USER_GENDER:-}
            LastName: ${ZITADEL_USER_LAST_NAME:?}
            NickName: ${ZITADEL_USER_NICK_NAME:-}
            Password: ${ZITADEL_USER_PASSWORD:?}
            PasswordChangeRequired: false
            Phone:
              Number: ${ZITADEL_USER_PHONE_NUMBER:-}
              Verified: true
            UserName: ${ZITADEL_USER_NAME:?}@${HOSTNAME:?}
      ...

name: identity-provider

networks:
  identity-provider:
  proxy_bridge:
    external: true

secrets:
  postgresql-root-pasword:
    environment: DATABASE_ROOT_USER_PASSWORD
  zitadel-master-key:
    environment: MASTER_KEY

services:
  pgbouncer:
    <<: *service
    configs:
      - gid: "70"
        mode: 0440
        source: pgbouncer-userlist
        target: /etc/pgbouncer/userlist.txt
        uid: "70"
    depends_on:
      postgresql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 32M
    environment:
      AUTH_TYPE: scram-sha-256
      DATABASE_URL: postgres://postgres@postgresql:5432/postgres
      DEFAULT_POOL_SIZE: 5
      DISABLE_PQEXEC: 1
      MIN_POOL_SIZE: 2
      POOL_MODE: transaction
    healthcheck:
      <<: *service-healthcheck
      test:
        - CMD
        - pg_isready
        - -d
        - postgres
        - -U
        - postgres
    image: edoburu/pgbouncer:v1.24.0-p1

  postgresql:
    <<: *service
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    configs:
      - gid: "70"
        mode: 0440
        source: postgresql
        target: /etc/postgresql/postgresql.conf
        uid: "70"
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgresql-root-pasword
    healthcheck:
      <<: *service-healthcheck
      test:
        - CMD
        - pg_isready
        - -d
        - postgres
        - -U
        - postgres
    image: postgres:17.4-alpine3.21
    secrets:
      - gid: "1000"
        mode: 0440
        source: postgresql-root-pasword
        target: /run/secrets/postgresql-root-pasword
        uid: "1000"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  zitadel:
    <<: *service
    command: >
      start
      --config /etc/zitadel/zitadel.yml
      --masterkeyFile /run/secrets/zitadel-master-key
    configs:
      - gid: "1000"
        mode: 0440
        source: zitadel-config
        target: /etc/zitadel/zitadel.yml
        uid: "1000"
    depends_on:
      zitadel-setup:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 256M
    healthcheck:
      <<: *service-healthcheck
      start_period: 40s
      test:
        - CMD
        - /app/zitadel
        - ready
        - --config
        - /etc/zitadel/zitadel.yml
    image: ghcr.io/zitadel/zitadel:v2.71.3
    labels:
      - traefik.enable=true
      - traefik.http.routers.zitadel.rule=Host("${HOSTNAME:?}")
      - traefik.http.services.zitadel.loadbalancer.server.port=8080
      - traefik.http.services.zitadel.loadbalancer.server.scheme=h2c
    networks:
      - identity-provider
      - proxy_bridge
    secrets:
      - gid: "1000"
        mode: 0440
        source: zitadel-master-key
        target: /run/secrets/zitadel-master-key
        uid: "1000"

  zitadel-init:
    <<: *job
    command:
      - |
          if [ ! -f /state/initialized ]; then
            zitadel init --config /etc/zitadel/zitadel.yml
            touch /state/initialized
          fi
    configs:
      - gid: "1000"
        mode: 0440
        source: zitadel-config
        target: /etc/zitadel/zitadel.yml
        uid: "1000"
    depends_on:
      pgbouncer:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 64M
    entrypoint: sh -c
    image: ghcr.io/zitadel/zitadel:v2.71.3-debug
    user: root
    volumes:
      - state:/state

  zitadel-setup:
    <<: *job
    command:
      - |
          ZITADEL_VERSION="$(zitadel -v)"
          if [ "$(cat /state/setup-version 2> /dev/null)" != "$$ZITADEL_VERSION" ]; then
            zitadel setup --init-projections \
              --masterkeyFile /run/secrets/zitadel-master-key \
              --steps /etc/zitadel/steps.yml \
              --config /etc/zitadel/zitadel.yml
            echo "$$ZITADEL_VERSION" > /state/setup-version
          fi
    configs:
      - gid: "1000"
        mode: 0440
        source: zitadel-config
        target: /etc/zitadel/zitadel.yml
        uid: "1000"
      - gid: "1000"
        mode: 0440
        source: zitadel-steps
        target: /etc/zitadel/steps.yml
        uid: "1000"
    depends_on:
      zitadel-init:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 128M
    entrypoint: sh -c
    image: ghcr.io/zitadel/zitadel:v2.71.3-debug
    secrets:
      - gid: "1000"
        mode: 0440
        source: zitadel-master-key
        target: /run/secrets/zitadel-master-key
        uid: "1000"
    user: root
    volumes:
      - state:/state

volumes:
  state:
...
