---
include:
  - compose.service.postgresql.yml
  - compose.service.zitadel-init.yml

name: identity_provider

networks:
  identity_provider:
  proxy_bridge:
    external: true

x-podman:
  in_pod: false
...
