---
configs:
  zitadel_setup:
    content: |
      ---
      FirstInstance:
        InstanceName: ${HOST_NAME:?}
        Org:
          Name: ${ZITADEL_ORGANIZATION_NAME:?}
          Human:
            DisplayName: ${ZITADEL_USER_FIRST_NAME:?} ${ZITADEL_USER_LAST_NAME:?}
            Email:
              Address: ${ZITADEL_USER_EMAIL_ADDRESS:?}
              Verified: true
            FirstName: ${ZITADEL_USER_FIRST_NAME:?}
            Gender: ${ZITADEL_USER_GENDER:-}
            LastName: ${ZITADEL_USER_LAST_NAME:?}
            NickName: ${ZITADEL_USER_NICK_NAME:-}
            Password: ${ZITADEL_USER_PASSWORD:?}
            PasswordChangeRequired: false
            Phone:
              Number: ${ZITADEL_USER_PHONE_NUMBER:-}
              Verified: true
            UserName: ${ZITADEL_USER_NAME:?}
          Machine:
            Machine:
              Username: cloud.skeleton.iac
              Name: Cloud Skeleton (IaC)
            MachineKey:
              Type: 1
      ...

services:
  zitadel_setup:
    command:
      - |
          ZITADEL_MASTER_KEY_FILE=/state/secrets/zitadel-master-key.txt
          if [ ! -f "$$ZITADEL_MASTER_KEY_FILE" ]; then
            tr -dc A-Za-z0-9 < /dev/urandom | head -c 32 > "$$ZITADEL_MASTER_KEY_FILE"
          fi
          STATE_FILE=/state/zitadel/last-known-version
          ZITADEL_VERSION_CURRENT="$(zitadel -v)"
          ZITADEL_VERSION_LAST_KNOWN="$(cat "$$STATE_FILE" 2> /dev/null)"
          if [ "$$ZITADEL_VERSION_LAST_KNOWN" != "$$ZITADEL_VERSION_CURRENT" ]; then
            zitadel setup --init-projections=true \
              --masterkeyFile "$$ZITADEL_MASTER_KEY_FILE" \
              --config /etc/zitadel/zitadel.yml \
              --steps /run/zitadel/setup.yml | \
              tee >(grep --line-buffered -m 1 '"type":"serviceaccount"' > /state/secrets/zitadel-cloud.skeleton.iac.json)
            echo "$$ZITADEL_VERSION_CURRENT" > "$$STATE_FILE"
          fi
    configs:
      - gid: "1000"
        mode: 0440
        source: zitadel_setup
        target: /run/zitadel/setup.yml
        uid: "1000"
    depends_on: !override
      zitadel_init:
        condition: service_completed_successfully
    extends:
      file: compose.service.zitadel-init.yml
      service: zitadel_init
    volumes:
      - ./state/secrets:/state/secrets
...
